### ISSUE TITLE
Ansible Tower AWS Workshop | Fix firewall service list that break deployment

### ISSUE THREAD

**Issue by dmc5179** [RedHatGov/redhatgov.workshops#115]
In 3_load.yml the following task fails due to httpd not being the correct service name. The correct service names are http and https

```
- name: Open ports 80,443 on nodes
  become: yes
  remote_user: ec2-user
  hosts:
    - rhel_nodes
  gather_facts: yes
  tasks:
    - name: open firewalld ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
      - 'httpd'
      - 'https'
    - name: restart service
      service:
        name: firewalld
        state: reloaded
```
